name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Fixed: removed extra asterisk
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update snake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to v3
      - uses: Platane/snk@v3       # Updated to v3
        id: snake-gif
        with:
          github_user_name: marvinok26
          svg_out_path: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
